[package]
name = "lnprpc"
description = "LNP node RPC API"
version = "0.5.0"
authors = ["Dr. Maxim Orlovsky <orlovsky@pandoracore.com>"]
license = "MIT"
keywords = ["bitcoin", "node", "lightning-network", "smart-contracts", "rpc"]
edition = "2018"
readme = "README.md"

[lib]
name = "lnprpc"

[dependencies]
amplify = "3.9.1"
strict_encoding = "1.7.5"
lnp-core = { version = "0.5.2", git = "https://github.com/LNP-BP/lnp-core" }
lnpbp = "0.5.0"
bitcoin = { version = "0.27.1", features = ["rand"] }
internet2 = "0.5.16"
microservices = { version = "0.6.0-beta.1", git = "https://github.com/internet2-org/rust-microservices", default-features = false }
descriptor-wallet = "0.5.1"
serde_crate = { package = "serde", version = "1", features = ["derive"], optional = true }
serde_with = { version = "1.8", optional = true }
serde_yaml = { version = "0.8.23", optional = true }
log = "0.4.14"
colored = "2.0.0"

[features]
default = ["serde"]
all = ["serde"]
serde = [
    "serde_crate", "serde_with", "serde_yaml", "bitcoin/use-serde",
    "amplify/serde", "internet2/serde", "microservices/serde",
    "lnpbp/serde", "descriptor-wallet/serde", "lnp-core/serde"
] #, "rgb-core/serde",  "rgb_node/serde" ]
