[package]
name = "lnp-cli"
version = "0.5.0"
edition = "2018"

[[bin]]
path = "src/main.rs"
name = "lnp-cli"

[dependencies]
lnp_node = { version = "0.5.0", path = "../node", features = ["cli"] }
microservices = "0.5.2"
clap = "=3.0.0-beta.5"
log = "0.4.14"
