[package]
name = "lnp-cli"
description = "LNP node command-line interface"
version = "0.5.0"
authors = ["Dr. Maxim Orlovsky <orlovsky@pandoracore.com>"]
license = "MIT"
keywords = ["bitcoin", "node", "lightning-network", "smart-contracts", "lnp"]
edition = "2018"
readme = "../README.md"
exclude = []

[[bin]]
path = "src/main.rs"
name = "lnp-cli"

[dependencies]
amplify = "3.10.0"
lnp-core = { version = "0.6.0-beta.1", git = "https://github.com/LNP-BP/lnp-core" }
lnp_rpc = { version = "0.6.0-beta.1", path = "../rpc" }
lightning-invoice = "0.13.0"
internet2 = "0.5.12"
microservices = { version = "0.6.0-beta.1", git = "https://github.com/internet2-org/rust-microservices", default-features = false, features = ["cli"] }
clap = { version = "=3.0.0-rc.7", features = ["derive"] }
log = "0.4.14"
